config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  
  as :user do
  get "signin",to: 'devise/sessions#new'
  get "signup" ,to: 'devise/registrations#new'
  delete "signout" ,to: 'devise/sessions#destroy'
  end
  get 'feed', to: 'feed#show'
ActiveAdmin.routes(self)
  resources :users,only: :show,param: :username do
    member do
      post 'follows' ,to: 'follows#create'
      delete 'unfollow',to: 'follows#destroy'
    end
  end
  resources :items do
    member do
     post 'vote',to: 'votes#create'
     delete 'unvote' ,to: 'votes#destroy'
    end
  end
  resources :tweets do
    resources :comments
end
  post 'create', to: 'comments#create'
  devise_for :views
  root 'pages#home'
  get 'about', to: 'pages#about'
    get 'contact', to: 'pages#contact'


end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  validates :content, presence: true,length: {maximum:140}
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_many :comments
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [ :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index,:show]
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  @tweet = Tweet.find(params[:id])

  @comment = @tweet.comments
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new

  end

  # GET /tweets/1/edit
  def edit

  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.new(tweet_params)
      if @tweet.save
         redirect_to @tweet, notice: 'Tweet was successfully created.'
      else
      render :new
      end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    @tweet = current_user.tweets.find(params[:id])
      if @tweet.update(tweet_params)
       redirect_to @tweet, notice: 'Tweet was successfully updated.'
      else
         render :edit
      end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
   redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = current_user.tweets.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:user_id,:content,:image)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_comment.html.erb
<%= form_for([@tweet,@tweet.comments.build]) do |form| %>
<div class="form-group">
  <%= form.label :comments? %>
  <%= form.text_field :content,class:"form-control" %>
</div>

<div class="actions">
  <%= form.submit class:"btn btn-primary" %>
</div>
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(tweet, html: {multipart:true}) do |form| %>
<% if tweet.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(tweet.errors.count, "error") %>
      prohibited this tweet from being saved:</h2>

    <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="form-group">
  <%= form.label :content %>
  <%= form.text_area :content,class:"form-control" %>
</div>

<div class="form-group">
  <%= form.label :image %>
  <%= form.file_field :image,class:"form-control" %>
</div>

<div class="actions">
  <%= form.submit class:"btn btn-primary" %>
</div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<div class="container">

  <!-- <h1>Tweets</h1> -->
  <div class="row">
    <% if user_signed_in? %>
      <!-- true -->
      <p>Your Account</p>
      <%=link_to current_user.username, user_path(current_user.username)%>
    <% else %>
      <%=link_to "Sign up now",signup_path%>
    <% end %>

    <table class='table-inverse inverse'>
      <thead>
        <tr>
          <th>User</th>
          <th>Content</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @tweets.each do |tweet| %>
          <tr>
            <%= link_to tweet,class:"list-group-action" do %>
            <td ="list-group-item-heading"><%= tweet.user.username %></td>
            <td>
              <% if tweet.image.present? %>
                <p><%=image_tag tweet.image.url,size:250 %></p>
              <% end %>
            </td>
            <td ="list-group-item-text"><%= tweet.content %></td>

          <% end %>
          <td><%= link_to 'Show', tweet %></td>
          <% if tweet.user == current_user %>
            <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
            <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>

        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
</div>
<% if user_signed_in? %>
  <%= link_to 'New Tweet', new_tweet_path %>
<% end %>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-8">

      <p>
        <strong>User:</strong>
        <%= @tweet.user.name %>
      </p>

      <p>
        <strong>Content:</strong>
        <%= @tweet.content %>
      </p>
      <strong>Pic:</strong>
      <%= image_tag @tweet.image.url,size:250 %>
    </p>

    <%@comment.each do |com| %>
      <%=com.content%>
      <br>
    <% end %>

    <br>
    <br>

    <br>

    <%= render 'tweets/comment' %>

    <% if @tweet.user == current_user %>
      <td><%= link_to 'Edit', edit_tweet_path(@tweet) %></td>
      <td><%= link_to 'Destroy', @tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>

    |
    <%= link_to 'Back', tweets_path %>
  </div>
</div>
</div>