config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  
  as :user do
  get "signin",to: 'devise/sessions#new'
  get "signup" ,to: 'devise/registrations#new'
  delete "signout" ,to: 'devise/sessions#destroy'
  end
  get 'feed', to: 'feed#show'
ActiveAdmin.routes(self)
  resources :users,only: :show,param: :username do
    member do
      post 'follows' ,to: 'follows#create'
      delete 'unfollow',to: 'follows#destroy'
    end
  end
  resources :items do
    member do
     post 'vote',to: 'votes#create'
     delete 'unvote' ,to: 'votes#destroy'
    end
  end
  resources :tweets do
    resources :comments
end
  post 'create', to: 'comments#create'
  devise_for :views
  root 'pages#home'
  get 'about', to: 'pages#about'
    get 'contact', to: 'pages#contact'


end

app/models/user.rb
class User < ApplicationRecord
  devise :omniauthable, :omniauth_providers => [:facebook]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :tweets
         has_many :items
         validates :username,presence: true,uniqueness: true, length: {minimum: 6}
          validates :name,presence: true
          acts_as_followable
            acts_as_follower
            acts_as_voter
               def self.from_omniauth(auth)
                  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
                  user.email = auth.info.email
                  user.password = Devise.friendly_token[0,20]
                end
               end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
     @user = User.from_omniauth(request.env["omniauth.auth"])
     sign_in_and_redirect @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(username:params[:username])
    @tweets = @user.tweets
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container">

  <div class="row">
    <% if user_signed_in? %>

      <% if current_user.following?(@user) %>
        <p><%= link_to "Unfollow", unfollow_user_path(@user.username),method: :delete%></p>
      <% else %>
        <p><%= link_to "follow", follows_user_path(@user.username),method: :post%></p>
      <% end %>
    <% end %>
    <table class='table-inverse inverse'>
      <thead>
        <tr>
          <th>Tweets</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @tweets.each do |tweet| %>
          <tr>
            <td><%= tweet.user.username %></td>
            <td><%= tweet.content %></td>

          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
  </div>

</div>