config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  
  as :user do
  get "signin",to: 'devise/sessions#new'
  get "signup" ,to: 'devise/registrations#new'
  delete "signout" ,to: 'devise/sessions#destroy'
  end
  get 'feed', to: 'feed#show'
ActiveAdmin.routes(self)
  resources :users,only: :show,param: :username do
    member do
      post 'follows' ,to: 'follows#create'
      delete 'unfollow',to: 'follows#destroy'
    end
  end
  resources :items do
    member do
     post 'vote',to: 'votes#create'
     delete 'unvote' ,to: 'votes#destroy'
    end
  end
  resources :tweets do
    resources :comments
end
  post 'create', to: 'comments#create'
  devise_for :views
  root 'pages#home'
  get 'about', to: 'pages#about'
    get 'contact', to: 'pages#contact'


end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  acts_as_votable
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show]
   before_action :authenticate_user!,except: [:index,:show]
  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = current_user.items.new
  end

  # GET /items/1/edit
  def edit
      @item = current_user.items.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
      @item = user.items.find(params[:id])
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = current_user.items.find(params[:id])
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :url, :text)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
<% if item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(item.errors.count, "error") %>
      prohibited this item from being saved:</h2>

    <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= form.label :title %>
  <%= form.text_field :title,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :url %>
  <%= form.text_field :url,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :text %>
  <%= form.text_field :text,class: "form-control" %>
</div>

<%= form.submit class: "btn btn-primary" %>
</div>
<% end %>

app/views/items/edit.html.erb
<div class="container">
  <h1>Editing Item</h1>

  <%= render 'form', item: @item %>

  <%= link_to 'Show', @item %>
  |
  <%= link_to 'Back', items_path %>
</div>

app/views/items/index.html.erb
<div class="container">

  <h1>Items</h1>

  <table>
    <thead>
      <tr>
        <th>Votes</th>
        <th>User</th>
        <th>Title</th>
        <th>Url</th>
        <th>Text</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.votes_for.up.size %></td>
          <td><%= item.user.email %></td>
          <td><%= item.title %></td>
          <td><%= item.url %></td>
          <td><%= item.text %></td>
          <td><%= link_to 'Show', item %></td>
          <% if user_signed_in? %>

            <% if current_user.voted_up_on? item %>
              <td><%= link_to 'Unvote',unvote_item_path(item),method: :delete %></td>
            <% else %>
              <td><%= link_to 'Vote', vote_item_path(item),method: :post %></td>
            <% end %>
          <% end %>
          <% if item.user == current_user %>
            <td><%= link_to 'Edit', edit_item_path(item) %></td>
            <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Item', new_item_path %>
</div>

app/views/items/new.html.erb
<div class="container">

  <h1>New Item</h1>

  <%= render 'form', item: @item %>

  <%= link_to 'Back', items_path %>

</div>

app/views/items/show.html.erb
<div class="container">

  <p>
    <strong>User:</strong>
    <%= @item.user.email %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @item.title %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= @item.url %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= @item.text %>
  </p>

  <% if @item.user == current_user %>
    <%= link_to 'Edit', edit_item_path(@item) %>
  <% end %>
  |
  <%= link_to 'Back', items_path %>

</div>